---
title: "R Notebook"
output: html_notebook
---

#Latihan 

#Nomor 1

```{r}
A <- matrix(c(5,-4,-1,1),2,2, TRUE)
A
b <- c(-10,2)
showEqn(A,b)
```

```{r}
Solve (A,b)
```
```{r}
plotEqn(A,b) #untuk SPL dengan 2 variabel
```
```{r}
echelon(A,b)
```
```{r}
echelon(A,b, verbose=TRUE)
```
```{r}
echelon(A,b, verbose = TRUE, fractions = TRUE)
```
#Nomor 2

```{r}
A <- matrix(c(4,-2,0,5,-2,1,3,4,-1), 3,3,TRUE)
A
b <- c(2,7,3)
showEqn(A,b)
```
```{r}
Solve (A,b)
```
```{r}
plotEqn3d(A,b)
```

```{r}
echelon(A,b, verbose = TRUE, fractions = TRUE)
```
#Nomor 3

```{r}
A <- matrix(c(1,1,1,2,3,5,4,0,5),3,3, TRUE)
A
b <- c(5,8,2)
showEqn(A,b)
```
```{r}
Solve(A,b)
```
```{r}
plotEqn3d(A,b)
```

```{r}
echelon(A,b, verbose = TRUE, fractions = TRUE)
```
#Nomor 4

```{r}
A <- matrix(c(2,5,1,-1,4,3,5,0,-2),3,3, TRUE)
A
b <- c(-12,-4,-13)
showEqn(A,b)
```
```{r}
Solve (A,b)
```
```{r}
plotEqn3d(A,b)
```

```{r}
echelon(A,b, verbose = TRUE, fractions = TRUE)
```


